### PR TITLE
Port github and auth scripts.

### PR DESCRIPTION
**Pull request by mjuvekar7**
Port github.coffee and auth.coffee from old GooeySr.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks for this :-)

Weirdly my bot crashes on trying to start, but seemingly in the `slap` script (ping @jellysnake). Am unsure if it is a problem in that script or a conflict vs the stuff in this PR. Or maybe I'm missing some config? I set the `HUBOT_AUTH_ADMIN` variable but is anything else needed, particularly for the GitHub parts? I expect I need to set something there and vaguely recall you mentioning something like that.

The `auth.coffee` has some nice intro doc in the script, while `github.coffee` doesn't have a whole lot. I figure that probably relates to using stuff from the parent script. Maybe a bit more about that and a link could be added to the doc?

Lets coordinate on IRC sometime when you're around. Ping me there :-) I'll be afk at times but should notice.

```
2016-12-18T20:50:03.128074+00:00 heroku[web.1]: State changed from crashed to starting
2016-12-18T20:50:04.928488+00:00 heroku[web.1]: Starting process with command `bin/hubot -a irc`
2016-12-18T20:50:10.635416+00:00 app[web.1]: [Sun Dec 18 2016 20:50:10 GMT+0000 (UTC)] ERROR Unable to load /app/scripts/slap: ReferenceError: robot is not defined
2016-12-18T20:50:10.635445+00:00 app[web.1]:   at Object.<anonymous> (/app/scripts/slap.coffee:10:1, <js>:4:3)
2016-12-18T20:50:10.635446+00:00 app[web.1]:   at Object.<anonymous> (/app/scripts/slap.coffee:10:1, <js>:33:4)
2016-12-18T20:50:10.635454+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-12-18T20:50:10.635455+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
2016-12-18T20:50:10.635466+00:00 app[web.1]:   at Module.load (/app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-12-18T20:50:10.635467+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-12-18T20:50:10.635468+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-12-18T20:50:10.635468+00:00 app[web.1]:   at require (module.js:380:17)
2016-12-18T20:50:10.635477+00:00 app[web.1]:   at Robot.loadFile (/app/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
2016-12-18T20:50:10.635478+00:00 app[web.1]:   at Robot.load (/app/node_modules/hubot/src/robot.coffee:377:9, <js>:247:30)
2016-12-18T20:50:10.635478+00:00 app[web.1]:   at IrcBot.loadScripts (/app/node_modules/hubot/bin/hubot:93:5, <js>:97:13)
2016-12-18T20:50:10.635479+00:00 app[web.1]:   at IrcBot.g (events.js:180:16)
2016-12-18T20:50:10.635480+00:00 app[web.1]:   at IrcBot.emit (events.js:92:17)
2016-12-18T20:50:10.635480+00:00 app[web.1]:   at IrcBot.run (/app/node_modules/hubot-irc/src/irc.coffee:337:5, <js>:429:19)
2016-12-18T20:50:10.635481+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
2016-12-18T20:50:10.635481+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
2016-12-18T20:50:10.635482+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
2016-12-18T20:50:10.635482+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-12-18T20:50:10.635490+00:00 app[web.1]: 
2016-12-18T20:50:10.706518+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by mjuvekar7** [comment]
Indeed, you have to set other variables for the github script. Check out the githubot readme https://github.com/iangreenleaf/githubot

**Comment by Cervator** [comment]
Thanks @mjuvekar7 :-)

I added another doc link real quick and made a couple messages nicer. The error was from the slap script and I talked to @jellysnake on IRC briefly. I couldn't get a fixed version working fast so I just commented it out in https://github.com/MovingBlocks/GooeyJr/commit/c1f76e982ab0c3b7d3c5bb348c90dd7e3bf5a33b for now and submitted #23 for us to fix it later.

Was able to test the role stuff and repo creation, nicely done :-) For some reason the bot didn't seem to find my test team. I switched it over to our Nanoware org but it might actually be better to keep using GooeyTests, mind adding me as an admin/owner over there sometime?

In any case merged this and approved the task :-)

**Comment by Cervator** [comment]
Oh, actually I sent the task back to you so you'll have to submit it back to review so we can approve it :-)

https://codein.withgoogle.com/dashboard/task-instances/6657025985478656/

**Pull request merged**
