### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by iojw**
- Removes mention of the deprecated cedar stack when creating the Heroku application through heroku-cli. Heroku will default to the latest stack.
- Typo fixes

### CODE REVIEW

**Comment by Cervator** [comment]
Trying to get back up to speed for testing :-)

Went through the readme (with the changes from this branch applied), opting for the Freenode approach supplying the extra 3 env vars. But not getting a bot. Too sleepy to go further tonight but thought I'd dump the log here for reference and less sleepy eyes tomorrow:


```
2018-10-15T06:29:25.723767+00:00 app[web.1]: 
2018-10-15T06:29:26.248734+00:00 heroku[web.1]: Restarting
2018-10-15T06:29:26.679116+00:00 app[web.1]: Mon, 15 Oct 2018 06:29:26 GMT body-parser deprecated undefined extended: provide extended option at node_modules/hubot/src/robot.js:445:21
2018-10-15T06:29:27.365863+00:00 app[web.1]: [Mon Oct 15 2018 06:29:27 GMT+0000 (UTC)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
2018-10-15T06:29:27.917886+00:00 app[web.1]: [Mon Oct 15 2018 06:29:27 GMT+0000 (UTC)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
2018-10-15T06:29:28.036812+00:00 app[web.1]: [Mon Oct 15 2018 06:29:28 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
2018-10-15T06:29:29.593704+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-10-15T06:29:29.703992+00:00 heroku[web.1]: Process exited with status 0
2018-10-15T06:29:39.405318+00:00 heroku[web.1]: Starting process with command `bin/hubot -a irc`
2018-10-15T06:29:45.246621+00:00 app[web.1]: audited 305 packages in 2.365s
2018-10-15T06:29:45.248033+00:00 app[web.1]: found 0 vulnerabilities
2018-10-15T06:29:45.248037+00:00 app[web.1]: 
2018-10-15T06:29:45.686879+00:00 app[web.1]: Mon, 15 Oct 2018 06:29:45 GMT body-parser deprecated undefined extended: provide extended option at node_modules/hubot/src/robot.js:445:21
2018-10-15T06:29:46.046525+00:00 app[web.1]: [Mon Oct 15 2018 06:29:46 GMT+0000 (UTC)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
2018-10-15T06:29:46.319751+00:00 app[web.1]: [Mon Oct 15 2018 06:29:46 GMT+0000 (UTC)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
2018-10-15T06:29:46.383775+00:00 app[web.1]: [Mon Oct 15 2018 06:29:46 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
2018-10-15T06:29:46.550923+00:00 heroku[web.1]: State changed from starting to up
```

**Comment by iojw** [comment]
Hmm I'm not sure.. I receive the same messages as you when GooeyJr boots and the bot joins the channel no problem. Maybe re-check your env variables? You can compare them to the ones set for the actual bot.

```
2018-10-15T13:46:55.635220+00:00 app[web.1]: audited 305 packages in 5.389s
2018-10-15T13:46:55.637069+00:00 app[web.1]: found 0 vulnerabilities
2018-10-15T13:46:55.637072+00:00 app[web.1]: 
2018-10-15T13:46:56.612039+00:00 app[web.1]: Mon, 15 Oct 2018 13:46:56 GMT body-parser deprecated undefined extended: provide extended option at node_modules/hubot/src/robot.js:445:21
2018-10-15T13:46:57.462663+00:00 app[web.1]: [Mon Oct 15 2018 13:46:57 GMT+0000 (UTC)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
2018-10-15T13:46:58.081455+00:00 heroku[web.1]: State changed from starting to up
2018-10-15T13:46:58.233529+00:00 app[web.1]: [Mon Oct 15 2018 13:46:58 GMT+0000 (UTC)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
2018-10-15T13:46:58.499444+00:00 app[web.1]: [Mon Oct 15 2018 13:46:58 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
2018-10-15T13:46:58.954790+00:00 app[web.1]: 15 Oct 13:46:58 - SEND: CAP REQ sasl
2018-10-15T13:46:58.955211+00:00 app[web.1]: 15 Oct 13:46:58 - Sending irc NICK/USER
2018-10-15T13:46:58.955343+00:00 app[web.1]: 15 Oct 13:46:58 - SEND: NICK GooeyJr
2018-10-15T13:46:58.955661+00:00 app[web.1]: 15 Oct 13:46:58 - SEND: USER GooeyJr 8 * :nodeJS IRC client
2018-10-15T13:47:01.322497+00:00 heroku[router]: at=info method=GET path="/" host=xxx request_id=xxx fwd="xxx" dyno=web.1 connect=2ms service=808ms status=200 bytes=225 protocol=https
2018-10-15T13:47:06.419142+00:00 app[web.1]: 15 Oct 13:47:06 - SEND: AUTHENTICATE PLAIN
2018-10-15T13:47:06.420827+00:00 app[web.1]: 15 Oct 13:47:06 - SEND: NICK GooeyJr1
2018-10-15T13:47:06.631300+00:00 app[web.1]: 15 Oct 13:47:06 - SEND: AUTHENTICATE
...
```

**Comment by syntaxi** [comment]
Managed to get it to work, had two hiccups.

1. The username for sasl apparently needs to be the same as the irc nick if you're using the bot.
2. We should possibly change the git commands to account for the fact that heroku only deploys from `master`, but the default here is `develop`. When I ran `git checkout master` and then `git push heroku master` it worked fine but I was getting issues when I ran without the checkout.

**Comment by syntaxi** [comment]
Managed to get it to work, had two hiccups.

1. The username for sasl apparently needs to be the same as the irc nick if you're using the bot.
2. We should possibly change the git commands to account for the fact that heroku only deploys from `master`, but the default here is `develop`. When I ran `git checkout master` and then `git push heroku master` it worked fine but I was getting issues when I ran without the checkout.

**Comment by iojw** [comment]
@jellysnake Updated the README to address your comments 🙂

**Pull request merged**
